### ISSUE TITLE
Model output occasionally returns Null

### ISSUE THREAD

**Issue by mhtess** [mhtess/rwebppl#48] opened 2017-01-30 21:48 UTC
Sometimes rwebppl is returning a `NULL` object to R. This may be due to multiple chains finishing at the same time.

**Comment by hawkrobe** [comment] 2017-01-31 20:25
This has been happening to me quite a bit, too (although I'm not running multiple chains...)

**Comment by mhtess** [comment] 2017-02-07 03:39
@hawkrobe and I discussed today that this is probably due to our dumb trigger for when to read from file, which is some number of seconds after the output file was created. It seems like we may want to address this and #22 in the same swoop, possibly by replacing our `system2` call with something from the [`subprocess`](https://github.com/lbartnik/subprocess) package

**Comment by mhtess** [comment] 2017-02-07 03:41
alternatively, we can create a shell script wrapper for the `system2` call, which runs webppl and then writes a file to signal the end.

**Comment by hawkrobe** [comment] 2017-02-09 19:43
Related to my comment on issue #45, I believe the issue is that we're currently using the *asynchronous* versions of `fs` functions: in particular, `fs.writeFile()` and `fs.rename()` are non-blocking, so that the `finally` block where the finish file is written doesn't wait for the output file to be written or renamed.

**Comment by hawkrobe** [comment] 2017-02-09 19:44
I propose we switch to the synchronous versions since we're not really getting anything from the asynchrony

**Comment by hawkrobe** [comment] 2017-02-10 20:11
Closed by PR #52

**Closed as completed by hawkrobe** 2017-02-10 20:11 UTC
